Tony133/nestjs-api-boilerplate-jwt

- LICENSE
- README.md
- package-lock.json
- package.json
- src/change-password/change-password.controller.ts
- src/forgot-password/forgot-password.controller.ts
- src/login/login.controller.ts
- src/main.ts
- src/register/register.controller.ts
- src/users/users.controller.ts
> Upgrade version nestjs v8

- .env.example
- README.md
- package-lock.json
- package.json
- src/app.module.ts
- src/change-password/change-password.module.ts
- src/change-password/change-password.service.ts
- src/forgot-password/forgot-password.module.ts
- src/forgot-password/forgot-password.service.ts
- src/mailer/mailer.module.ts
- src/mailer/mailer.service.spec.ts
- src/mailer/mailer.service.ts
- src/register/register.module.ts
- src/register/register.service.ts
- src/users/entities/users.entity.ts
- src/users/users.module.ts
> Added mailer module

- nest-cli.json
- package-lock.json
- package.json
- src/change-password/change-password.controller.ts
- src/forgot-password/forgot-password.controller.ts
- src/login/login.controller.ts
- src/main.ts
- src/register/register.controller.ts
- src/users/users.controller.ts
> Add open api swagger

- README.md
- src/repl.ts
> feat: add repl mode

- test/app.e2e-spec.ts
- test/change-password/change-password.e2e-spec.ts
- test/forgot-password/forgot-password.e2e-spec.ts
- test/login/login.e2e-spec.ts
- test/register/register.e2e-spec.ts
- test/users/users.e2e-spec.ts
> test: added test e2e

- package.json
- src/app.controller.spec.ts
- src/change-password/change-password.controller.spec.ts
Update unit test and config jest
> test(): update unit test

- package-lock.json
- package.json
- src/iam/change-password/change-password.service.spec.ts
- src/iam/change-password/change-password.service.ts
- src/iam/forgot-password/forgot-password.service.spec.ts
- src/iam/forgot-password/forgot-password.service.ts
- src/iam/register/register.service.spec.ts
- src/iam/register/register.service.ts
-  Update IAM modules
-  Update dependencies:
-   mysql2 `v3.1.2` and typeorm `v0.3.12`
> chore: update iam modules

- pnpm-lock.yaml
- src/iam/login/login.service.spec.ts
- src/iam/login/login.service.ts
- src/users/users.controller.spec.ts
- src/users/users.controller.ts
- src/users/users.service.spec.ts
I also removed a few bogus tests I saw. I'm sure there's more, but didn't go looking for them.
> tests: update tests to bring better coverage

- .github/workflows/nodejs-environment.yml
- test/app.e2e-spec.ts
- test/change-password/change-password.e2e-spec.ts
- test/forgot-password/forgot-password.e2e-spec.ts
- test/users/users.e2e-spec.ts
> tests(e2e): improvements

- README.md
> chore(): update readme.md

- tsconfig.json
- Added property `strict` and `paths`in the `tsconfig.json`
> chore(): update tsconfig.json

- src/app.controller.ts
> chore(): removed unused import

- .prettierrc
- Added property `printWidth` in the `.prettierrc` config
> chore(): update prettier

- .github/workflows/nodejs-environment.yml
- Removed node version `16.x` and added version `20.x`
> chore: update nodejs-environment.yml

- package.json
- pnpm-lock.yaml
- src/helpers/configure-auth-swagger-docs.helper.ts
- src/helpers/configure-swagger-docs.helper.ts
- src/main.ts
- Update configure swagger docs
> refactor: update configure swagger docs

- package.json
- pnpm-lock.yaml
- src/shared/logger/logger.module.ts
- src/shared/logger/logger.service.ts
- Added custom logger with pino
> feat: added custom logger with pino

- docker-compose.yml
Update docker-compose.yml, remove version
> chore: update docker-compose.yml

- eslint.config.js
- package.json
> chore: update eslint config

- package.json
- pnpm-lock.yaml
- src/app.module.ts
- src/helpers/validation-schema-env.ts
Improvement in the validation of env files
> chore: improvement in the validation of env files

- src/common/mailer/mailer.service.ts
- src/iam/change-password/change-password.controller.ts
- src/iam/change-password/change-password.service.ts
- src/iam/forgot-password/forgot-password.controller.ts
- src/iam/forgot-password/forgot-password.service.ts
- src/iam/login/login.controller.ts
- src/iam/login/login.service.ts
- src/iam/register/register.controller.ts
- src/iam/register/register.service.ts
- src/users/users.controller.ts
removed a few any types so as to in-robusten the code a bit
> chore: update codebase with safe-type

- package.json
- pnpm-lock.yaml
> chore: update dependencies fastify

- package.json
- pnpm-lock.yaml
- update dependencie typescript
> chore: update dependencie typescript

- package.json
- pnpm-lock.yaml
> chore: update dependencies nest

- package.json
- pnpm-lock.yaml
> chore: update dependencie mysql

- package.json
- pnpm-lock.yaml
> chore: update dependencie typeorm
